#!/bin/bash
SERVICE="#service_name"

if systemctl is-active --quiet $SERVICE; then
    echo "$SERVICE is running."
else
    echo "$SERVICE is down. Starting now..."
    sudo systemctl start $SERVICE
fi
